# Generated by Django 6.0.4 on 2026-04-13 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование клиента')),
                ('phone', models.CharField(max_length=30, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО водителя')),
                ('phone', models.CharField(max_length=30, unique=True, verbose_name='Телефон')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='Номер удостоверения')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статусы заявок',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='Гос. номер')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('capacity_tons', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Грузоподъемность, т')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Менеджер по логистике'), ('leader', 'Руководитель'), ('admin', 'Администратор')], default='manager', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransportationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo_name', models.CharField(max_length=255, verbose_name='Груз')),
                ('cargo_weight', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Вес груза, т')),
                ('route_from', models.CharField(max_length=255, verbose_name='Пункт отправления')),
                ('route_to', models.CharField(max_length=255, verbose_name='Пункт назначения')),
                ('transportation_date', models.DateField(verbose_name='Дата перевозки')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость, ₽')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='logistics.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='logistics.requeststatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка на перевозку',
                'verbose_name_plural': 'Заявки на перевозку',
                'ordering': ['-transportation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departure_at', models.DateTimeField(blank=True, null=True, verbose_name='Выезд')),
                ('arrival_at', models.DateTimeField(blank=True, null=True, verbose_name='Прибытие')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transportations', to='logistics.driver', verbose_name='Водитель')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transportation', to='logistics.transportationrequest', verbose_name='Заявка')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transportations', to='logistics.vehicle', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Перевозка',
                'verbose_name_plural': 'Перевозки',
            },
        ),
    ]
