# Generated by Django 6.0.4 on 2026-04-16 16:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportation',
            options={'ordering': ['-assigned_at', '-created_at'], 'verbose_name': 'Перевозка', 'verbose_name_plural': 'Перевозки'},
        ),
        migrations.AddField(
            model_name='transportation',
            name='assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата назначения'),
        ),
        migrations.AddField(
            model_name='transportationrequest',
            name='cargo_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Объем груза, м3'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='arrival_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='departure_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='transportationrequest',
            name='cargo_name',
            field=models.CharField(max_length=255, verbose_name='Описание груза'),
        ),
        migrations.AlterField(
            model_name='transportationrequest',
            name='cargo_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Масса груза, т'),
        ),
        migrations.AlterField(
            model_name='transportationrequest',
            name='route_from',
            field=models.CharField(max_length=255, verbose_name='Адрес загрузки'),
        ),
        migrations.AlterField(
            model_name='transportationrequest',
            name='route_to',
            field=models.CharField(max_length=255, verbose_name='Адрес выгрузки'),
        ),
        migrations.CreateModel(
            name='RequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='logistics.transportationrequest', verbose_name='Заявка')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_entries', to='logistics.requeststatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'История статуса заявки',
                'verbose_name_plural': 'История статусов заявок',
                'ordering': ['-changed_at', '-id'],
            },
        ),
    ]
