# Generated by Django 6.0.4 on 2026-04-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_transportation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationrequest',
            name='cargo_type',
            field=models.CharField(choices=[('sand', 'Песок'), ('crushed_stone', 'Щебень'), ('concrete', 'Бетон')], default='sand', max_length=20, verbose_name='Тип груза'),
        ),
    ]
