# Generated by Django 6.0.4 on 2026-06-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_transportationrequest_cargo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='distance_customer_to_loading_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Заказчик - место погрузки, км'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='distance_loading_to_customer_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Погрузка - заказчик, км'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='distance_parking_to_loading_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Стоянка - место погрузки, км'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='trip_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество рейсов ТС'),
        ),
    ]
