# Generated by Django 6.0.4 on 2026-06-12 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_transportation_distance_customer_to_loading_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportations', to='logistics.transportationrequest', verbose_name='Заявка'),
        ),
    ]
